export const cyberSections = {
  foundations: [
    "foundations-f0-what-security-is",
    "foundations-f1-risk-and-outcomes",
    "foundations-f2-data-and-integrity",
    "foundations-f3-networks-and-transport",
    "foundations-f4-cia-and-simple-attacks",
    "foundations-f5-identity-and-access",
    "foundations-f6-human-factors-and-phishing",
    "foundations-f7-privacy-and-everyday-data-protection",
    "foundations-f8-foundations-capstone",
  ],
  applied: [
    "applied-a1-threat-modelling-as-design",
    "applied-a2-identity-and-access-control",
    "applied-a3-web-app-security",
    "applied-a4-api-and-service-security",
    "applied-a5-verification-and-release-gates",
    "applied-a6-logging-and-detection-basics",
    "applied-a7-applied-capstone",
  ],
  practice: [
    "practice-p1-secure-sdlc",
    "practice-p3-runtime-and-cloud-security",
    "practice-p2-exposure-reduction-zero-trust",
    "practice-p5-vulnerability-management",
    "practice-p6-detection-and-incident-response",
    "practice-p4-supply-chain-security",
    "practice-p7-privacy-ethics-auditability",
    "practice-p8-system-ilities",
    "practice-p9-capstone-professional-practice",
  ],
  summary: [],
};
