export const cyberSections = {
  foundations: [
    "foundations-f0-what-security-is",
    "foundations-f1-risk-and-outcomes",
    "foundations-f2-data-and-integrity",
    "foundations-f3-networks-and-transport",
    "foundations-f4-cia-and-simple-attacks",
    "foundations-f5-identity-and-access",
    "foundations-f6-human-factors-and-phishing",
    "foundations-f7-privacy-and-everyday-data-protection",
  ],
  applied: [
    "applied-welcome-prerequisites",
    "applied-threat-modeling-practice",
    "applied-vulnerability-exploitation",
    "applied-authentication-sessions",
    "applied-detection-response",
    "applied-risk-attack-chains",
    "applied-checkpoint-labs",
  ],
  practice: [
    "practice-welcome-mastery",
    "practice-secure-architecture",
    "practice-cryptography-practice",
    "practice-devsecops-sdlc",
    "practice-security-operations",
    "practice-vulnerability-management",
    "practice-governance-risk-compliance",
    "practice-capstone-portfolio",
  ],
  summary: [],
};
