export const cyberSections = {
  foundations: [
    "foundations-f0-what-security-is",
    "foundations-f1-risk-and-outcomes",
    "foundations-f2-data-and-integrity",
    "foundations-f3-networks-and-transport",
    "foundations-f4-cia-and-simple-attacks",
    "foundations-f5-identity-and-access",
    "foundations-f6-human-factors-and-phishing",
    "foundations-f7-privacy-and-everyday-data-protection",
    "foundations-f8-foundations-capstone",
  ],
  applied: [
    "applied-a1-threat-modelling-as-design",
    "applied-a2-identity-and-access-control",
    "applied-a3-web-app-security",
    "applied-a4-api-and-service-security",
    "applied-a5-verification-and-release-gates",
    "applied-a6-logging-and-detection-basics",
    "applied-a7-applied-capstone",
  ],
  practice: [
    "practice-p0-crypto-in-practice",
    "practice-p1-secure-architecture-zero-trust",
    "practice-p2-detection-and-incident-response",
    "practice-p3-supply-chain-risk",
    "practice-p4-adversarial-tradeoffs",
    "practice-p5-governance-and-professional-practice",
    "practice-p6-capstone",
  ],
  summary: [],
};
