export const softwareArchitectureSectionManifest = {
  foundations: [
    "soft-arch-foundations-discovery-requirements",
    "soft-arch-foundations-architecture-design",
    "soft-arch-foundations-implementation",
    "soft-arch-foundations-verification-testing",
    "soft-arch-foundations-deployment-cicd",
    "soft-arch-foundations-operations",
    "soft-arch-foundations-osi-diagnostics",
    "soft-arch-foundations-ilities-framework",
    "soft-arch-foundations-assessment",
  ],
  intermediate: [
    "soft-arch-intermediate-advanced-security",
    "soft-arch-intermediate-cloud-native-patterns",
    "soft-arch-intermediate-performance-engineering",
    "soft-arch-intermediate-data-architecture",
    "soft-arch-intermediate-service-decomposition",
    "soft-arch-intermediate-infrastructure-as-code",
    "soft-arch-intermediate-assessment",
  ],
  advanced: [
    "soft-arch-advanced-enterprise-frameworks",
    "soft-arch-advanced-compliance-architectures",
    "soft-arch-advanced-finops",
    "soft-arch-advanced-chaos-engineering",
    "soft-arch-advanced-governance",
    "soft-arch-advanced-multi-cloud",
    "soft-arch-advanced-legacy-modernisation",
    "soft-arch-advanced-capstone",
    "soft-arch-advanced-assessment",
  ],
  summary: [
    "soft-arch-summary-you-made-it",
    "soft-arch-summary-big-picture",
    "soft-arch-summary-games-labs",
    "soft-arch-summary-next-steps",
  ],
};
