"use client";

import React, { useState } from "react";
import Link from "next/link";
import ToolShell from "@/components/tools/ToolShell";
import { getToolContract } from "@/lib/tools/loadContract";
import { createToolError } from "@/components/tools/ErrorPanel";
import type { ToolContract, ExecutionMode } from "@/components/tools/ToolShell";

const contract = getToolContract("metrics-definition-studio");

export default function MetricsDefinitionStudioPage() {
  const [metricName, setMetricName] = useState("");
  const [definition, setDefinition] = useState("");
  const [calculation, setCalculation] = useState("");
  const [units, setUnits] = useState("");
  const [source, setSource] = useState("");

  if (!contract) {
    return (
      <div className="mx-auto max-w-4xl p-6">
        <p className="text-red-600">Tool contract not found.</p>
      </div>
    );
  }

  const handleRun = async (mode: ExecutionMode, inputs: Record<string, unknown>) => {
    const name = inputs.metricName as string;
    const def = inputs.definition as string;
    const calc = inputs.calculation as string;
    const unit = inputs.units as string;
    const src = inputs.source as string;

    if (!name || name.trim().length === 0) {
      return {
        success: false,
        error: createToolError("validation_error", "metrics-definition-studio", { field: "metricName" }),
      };
    }

    if (!def || def.trim().length === 0) {
      return {
        success: false,
        error: createToolError("validation_error", "metrics-definition-studio", { field: "definition" }),
      };
    }

    const json = {
      metricName: name,
      definition: def,
      calculation: calc || "Not specified",
      units: unit || "Not specified",
      source: src || "Not specified",
      lastUpdated: new Date().toISOString(),
    };

    const markdown = `# Metric Definition: ${name}

## Definition
${def}

## Calculation
${calc || "Not specified"}

## Units
${unit || "Not specified"}

## Data Source
${src || "Not specified"}

## JSON Specification
\`\`\`json
${JSON.stringify(json, null, 2)}
\`\`\`

---
*Generated by RansfordsNotes Metrics Definition Studio*`;

    return { success: true, output: markdown };
  };

  return (
    <div className="mx-auto max-w-6xl p-6">
      <nav className="mb-4">
        <Link href="/tools" className="text-sm font-semibold text-blue-700 hover:underline">
          ← Back to Tools
        </Link>
      </nav>

      <ToolShell contract={contract} onRun={handleRun} initialInputs={{ metricName, definition, calculation, units, source }}>
        <div className="space-y-4">
          <div>
            <label htmlFor="metricName" className="block text-sm font-semibold text-slate-900">
              Metric Name <span className="text-red-600">*</span>
            </label>
            <input
              id="metricName"
              type="text"
              value={metricName}
              onChange={(e) => setMetricName(e.target.value)}
              maxLength={200}
              className="mt-2 w-full rounded-lg border border-slate-300 p-3 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
              placeholder="e.g., Daily Active Users (DAU)"
            />
          </div>
          <div>
            <label htmlFor="definition" className="block text-sm font-semibold text-slate-900">
              Definition <span className="text-red-600">*</span>
            </label>
            <textarea
              id="definition"
              value={definition}
              onChange={(e) => setDefinition(e.target.value)}
              rows={3}
              maxLength={1000}
              className="mt-2 w-full rounded-lg border border-slate-300 p-3 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
              placeholder="What does this metric measure?"
            />
          </div>
          <div>
            <label htmlFor="calculation" className="block text-sm font-semibold text-slate-900">
              Calculation
            </label>
            <textarea
              id="calculation"
              value={calculation}
              onChange={(e) => setCalculation(e.target.value)}
              rows={4}
              maxLength={2000}
              className="mt-2 w-full rounded-lg border border-slate-300 p-3 font-mono text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
              placeholder="How is it calculated? (e.g., COUNT(DISTINCT user_id) WHERE ...)"
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label htmlFor="units" className="block text-sm font-semibold text-slate-900">
                Units
              </label>
              <input
                id="units"
                type="text"
                value={units}
                onChange={(e) => setUnits(e.target.value)}
                maxLength={50}
                className="mt-2 w-full rounded-lg border border-slate-300 p-3 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
                placeholder="e.g., Count, %, $"
              />
            </div>
            <div>
              <label htmlFor="source" className="block text-sm font-semibold text-slate-900">
                Data Source
              </label>
              <input
                id="source"
                type="text"
                value={source}
                onChange={(e) => setSource(e.target.value)}
                maxLength={500}
                className="mt-2 w-full rounded-lg border border-slate-300 p-3 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
                placeholder="e.g., User activity logs"
              />
            </div>
          </div>
        </div>
      </ToolShell>
    </div>
  );
}

