"use client";

import React, { useState } from "react";
import Link from "next/link";
import { ArrowLeft, FileCode, HelpCircle, Plus, Trash2, Download, CheckCircle2 } from "lucide-react";
import SecureErrorBoundary from "@/components/studios/SecureErrorBoundary";
import StudioNavigation from "@/components/studios/StudioNavigation";
import HelpTooltip from "@/components/studios/HelpTooltip";
import CreditEstimate from "@/components/studios/CreditEstimate";

interface Endpoint {
  id: string;
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
  path: string;
  description: string;
  requestBody?: string;
  responseBody?: string;
}

export default function APIDesignerPage() {
  const [apiName, setApiName] = useState("");
  const [apiVersion, setApiVersion] = useState("1.0.0");
  const [endpoints, setEndpoints] = useState<Endpoint[]>([]);
  const [generated, setGenerated] = useState(false);
  const [openApiSpec, setOpenApiSpec] = useState<string>("");

  function addEndpoint() {
    setEndpoints([
      ...endpoints,
      {
        id: Date.now().toString(),
        method: "GET",
        path: "/api/example",
        description: "",
      },
    ]);
  }

  function removeEndpoint(id: string) {
    setEndpoints(endpoints.filter((e) => e.id !== id));
  }

  function updateEndpoint(id: string, updates: Partial<Endpoint>) {
    setEndpoints(endpoints.map((e) => (e.id === id ? { ...e, ...updates } : e)));
  }

  function generateOpenAPI() {
    if (!apiName.trim()) {
      alert("Please enter an API name");
      return;
    }

    if (endpoints.length === 0) {
      alert("Please add at least one endpoint");
      return;
    }

    const spec = {
      openapi: "3.0.0",
      info: {
        title: apiName,
        version: apiVersion,
        description: "API generated by Ransford's Notes API Designer",
      },
      paths: endpoints.reduce((acc, endpoint) => {
        const path = endpoint.path.startsWith("/") ? endpoint.path : `/${endpoint.path}`;
        if (!acc[path]) acc[path] = {};
        acc[path][endpoint.method.toLowerCase()] = {
          summary: endpoint.description || `${endpoint.method} ${endpoint.path}`,
          responses: {
            "200": {
              description: "Successful response",
              content: endpoint.responseBody
                ? {
                    "application/json": {
                      schema: { type: "object" },
                      example: JSON.parse(endpoint.responseBody || "{}"),
                    },
                  }
                : undefined,
            },
          },
          ...(endpoint.requestBody && {
            requestBody: {
              content: {
                "application/json": {
                  schema: { type: "object" },
                  example: JSON.parse(endpoint.requestBody || "{}"),
                },
              },
            },
          }),
        };
        return acc;
      }, {} as Record<string, any>),
    };

    setOpenApiSpec(JSON.stringify(spec, null, 2));
    setGenerated(true);
  }

  function handleDownload() {
    if (!openApiSpec) return;
    const blob = new Blob([openApiSpec], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${apiName || "api"}-openapi.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function handleReset() {
    setApiName("");
    setApiVersion("1.0.0");
    setEndpoints([]);
    setGenerated(false);
    setOpenApiSpec("");
  }

  return (
    <SecureErrorBoundary studio="dev-studio">
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/30 to-slate-50">
        <div className="mx-auto max-w-7xl px-4 py-6 sm:py-8 sm:px-6 lg:px-8">
          <header className="mb-6 sm:mb-8">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
              <div className="flex items-center gap-3">
                <Link
                  href="/dev-studio"
                  className="text-slate-600 hover:text-slate-900 transition-colors"
                  aria-label="Back to Dev Studio"
                >
                  <ArrowLeft className="w-5 h-5" />
                </Link>
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-blue-600 text-white">
                  <FileCode className="w-6 h-6" />
                </div>
                <div>
                  <h1 className="text-3xl sm:text-4xl font-bold text-slate-900">API Designer</h1>
                  <p className="text-base sm:text-lg text-slate-600 mt-1">
                    Design, test, and document APIs with OpenAPI export
                  </p>
                </div>
                <HelpTooltip
                  title="API Designer"
                  content={
                    <div className="space-y-4">
                      <p>
                        The API Designer helps you design APIs (Application Programming Interfaces) that let 
                        different programs talk to each other.
                      </p>
                      <div>
                        <h3 className="font-semibold text-slate-900 mb-2">Features:</h3>
                        <ul className="list-disc list-inside space-y-1 text-sm text-slate-700">
                          <li>Define API endpoints and methods</li>
                          <li>Specify request/response schemas</li>
                          <li>Test API endpoints</li>
                          <li>Export OpenAPI/Swagger documentation</li>
                        </ul>
                      </div>
                    </div>
                  }
                />
              </div>
              <StudioNavigation studioType="dev" showHub={true} />
            </div>
          </header>

          <div className="rounded-3xl bg-white border border-slate-200 p-8 shadow-sm">
            {/* Credit Estimate */}
            <div className="mb-6">
              <CreditEstimate toolId="dev-studio-api-designer" />
            </div>

            {!generated ? (
              <div className="space-y-6">
                {/* API Info */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-2">
                      API Name
                    </label>
                    <input
                      type="text"
                      value={apiName}
                      onChange={(e) => setApiName(e.target.value)}
                      placeholder="My Awesome API"
                      className="w-full rounded-lg border border-slate-300 px-4 py-2 text-slate-900 focus:border-blue-500 focus:ring-2 focus:ring-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-2">
                      Version
                    </label>
                    <input
                      type="text"
                      value={apiVersion}
                      onChange={(e) => setApiVersion(e.target.value)}
                      placeholder="1.0.0"
                      className="w-full rounded-lg border border-slate-300 px-4 py-2 text-slate-900 focus:border-blue-500 focus:ring-2 focus:ring-blue-500"
                    />
                  </div>
                </div>

                {/* Endpoints */}
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <label className="block text-sm font-medium text-slate-700">
                      API Endpoints
                    </label>
                    <button
                      onClick={addEndpoint}
                      className="flex items-center gap-2 px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-semibold transition-colors"
                    >
                      <Plus className="w-4 h-4" />
                      Add Endpoint
                    </button>
                  </div>

                  <div className="space-y-4">
                    {endpoints.map((endpoint) => (
                      <div
                        key={endpoint.id}
                        className="p-4 rounded-lg border border-slate-200 bg-slate-50"
                      >
                        <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 mb-3">
                          <select
                            value={endpoint.method}
                            onChange={(e) =>
                              updateEndpoint(endpoint.id, {
                                method: e.target.value as Endpoint["method"],
                              })
                            }
                            className="rounded-lg border border-slate-300 px-3 py-2 text-slate-900 focus:border-blue-500 focus:ring-2 focus:ring-blue-500"
                          >
                            <option value="GET">GET</option>
                            <option value="POST">POST</option>
                            <option value="PUT">PUT</option>
                            <option value="DELETE">DELETE</option>
                            <option value="PATCH">PATCH</option>
                          </select>
                          <input
                            type="text"
                            value={endpoint.path}
                            onChange={(e) => updateEndpoint(endpoint.id, { path: e.target.value })}
                            placeholder="/api/users"
                            className="sm:col-span-2 rounded-lg border border-slate-300 px-3 py-2 text-slate-900 focus:border-blue-500 focus:ring-2 focus:ring-blue-500"
                          />
                          <button
                            onClick={() => removeEndpoint(endpoint.id)}
                            className="flex items-center justify-center gap-2 px-3 py-2 bg-red-50 hover:bg-red-100 text-red-600 rounded-lg transition-colors"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                        <input
                          type="text"
                          value={endpoint.description}
                          onChange={(e) =>
                            updateEndpoint(endpoint.id, { description: e.target.value })
                          }
                          placeholder="Endpoint description"
                          className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 mb-2"
                        />
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                          <textarea
                            value={endpoint.requestBody || ""}
                            onChange={(e) =>
                              updateEndpoint(endpoint.id, { requestBody: e.target.value })
                            }
                            placeholder='Request body (JSON) e.g. {"name": "string"}'
                            className="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 font-mono"
                            rows={3}
                          />
                          <textarea
                            value={endpoint.responseBody || ""}
                            onChange={(e) =>
                              updateEndpoint(endpoint.id, { responseBody: e.target.value })
                            }
                            placeholder='Response body (JSON) e.g. {"id": 1, "name": "string"}'
                            className="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 font-mono"
                            rows={3}
                          />
                        </div>
                      </div>
                    ))}
                  </div>

                  {endpoints.length === 0 && (
                    <div className="text-center py-8 text-slate-500">
                      <FileCode className="w-12 h-12 mx-auto mb-2 opacity-50" />
                      <p>No endpoints added yet. Click "Add Endpoint" to get started.</p>
                    </div>
                  )}
                </div>

                {/* Generate Button */}
                <div className="pt-4">
                  <button
                    onClick={generateOpenAPI}
                    disabled={!apiName.trim() || endpoints.length === 0}
                    className="w-full sm:w-auto px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Generate OpenAPI Specification
                  </button>
                </div>
              </div>
            ) : (
              <div className="space-y-6">
                <div className="flex items-center gap-2 text-emerald-600">
                  <CheckCircle2 className="w-5 h-5" />
                  <span className="font-semibold">OpenAPI specification generated successfully!</span>
                </div>

                {/* OpenAPI Preview */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-900 mb-3">OpenAPI Specification</h3>
                  <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 max-h-96 overflow-y-auto">
                    <pre className="text-xs font-mono text-slate-700 whitespace-pre-wrap">
                      {openApiSpec}
                    </pre>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex flex-col sm:flex-row gap-3">
                  <button
                    onClick={handleDownload}
                    className="flex items-center justify-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-semibold transition-colors"
                  >
                    <Download className="w-4 h-4" />
                    Download OpenAPI Spec
                  </button>
                  <button
                    onClick={handleReset}
                    className="px-6 py-3 bg-white hover:bg-slate-50 text-slate-900 border border-slate-300 rounded-lg font-semibold transition-colors"
                  >
                    Design Another API
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </SecureErrorBoundary>
  );
}
