"use client";

import React, { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Code, HelpCircle, Download, FileCode, Folder, CheckCircle2 } from "lucide-react";
import SecureErrorBoundary from "@/components/studios/SecureErrorBoundary";
import StudioNavigation from "@/components/studios/StudioNavigation";
import HelpTooltip from "@/components/studios/HelpTooltip";
import CreditEstimate from "@/components/studios/CreditEstimate";

type ProjectType = "website" | "api" | "mobile" | "desktop" | "library" | "cli";
type Stack = "react" | "vue" | "nextjs" | "express" | "fastapi" | "django" | "react-native" | "flutter" | "electron" | "tauri" | "node";

interface ProjectConfig {
  name: string;
  type: ProjectType;
  stack: Stack[];
  features: string[];
}

export default function ProjectsPage() {
  const [projectName, setProjectName] = useState("");
  const [projectType, setProjectType] = useState<ProjectType>("website");
  const [selectedStack, setSelectedStack] = useState<Stack[]>([]);
  const [selectedFeatures, setSelectedFeatures] = useState<string[]>([]);
  const [generated, setGenerated] = useState(false);
  const [projectStructure, setProjectStructure] = useState<Record<string, string>>({});

  const projectTypes: { value: ProjectType; label: string; description: string }[] = [
    { value: "website", label: "Website", description: "Frontend web application" },
    { value: "api", label: "API", description: "Backend API service" },
    { value: "mobile", label: "Mobile App", description: "Mobile application" },
    { value: "desktop", label: "Desktop App", description: "Desktop application" },
    { value: "library", label: "Library", description: "Reusable code library" },
    { value: "cli", label: "CLI Tool", description: "Command-line interface tool" },
  ];

  const stacks: Record<ProjectType, { value: Stack; label: string }[]> = {
    website: [
      { value: "react", label: "React" },
      { value: "vue", label: "Vue.js" },
      { value: "nextjs", label: "Next.js" },
    ],
    api: [
      { value: "express", label: "Express.js" },
      { value: "fastapi", label: "FastAPI" },
      { value: "django", label: "Django" },
    ],
    mobile: [
      { value: "react-native", label: "React Native" },
      { value: "flutter", label: "Flutter" },
    ],
    desktop: [
      { value: "electron", label: "Electron" },
      { value: "tauri", label: "Tauri" },
    ],
    library: [
      { value: "react", label: "React Component" },
    ],
    cli: [
      { value: "node" as Stack, label: "Node.js CLI" },
    ],
  };

  const availableFeatures: Record<ProjectType, string[]> = {
    website: ["TypeScript", "Tailwind CSS", "ESLint", "Prettier", "Testing", "PWA"],
    api: ["TypeScript", "Database", "Authentication", "API Documentation", "Testing", "Docker"],
    mobile: ["TypeScript", "Navigation", "State Management", "Testing", "CI/CD"],
    desktop: ["TypeScript", "Auto-updater", "Packaging", "Testing"],
    library: ["TypeScript", "Build Tools", "Documentation", "Testing"],
    cli: ["TypeScript", "CLI Framework", "Testing"],
  };

  function generateProjectStructure(config: ProjectConfig): Record<string, string> {
    const structure: Record<string, string> = {};
    const name = config.name || "my-project";

    // Base structure
    structure[`${name}/README.md`] = `# ${config.name || "My Project"}\n\nGenerated by Ransford's Notes Project Builder.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`;

    // Package.json
    const dependencies: Record<string, string> = {};
    if (config.stack.includes("react")) {
      dependencies.react = "^18.2.0";
      dependencies["react-dom"] = "^18.2.0";
    }
    if (config.stack.includes("nextjs")) {
      dependencies.next = "^14.0.0";
      dependencies.react = "^18.2.0";
      dependencies["react-dom"] = "^18.2.0";
    }
    if (config.stack.includes("express")) {
      dependencies.express = "^4.18.0";
    }

    structure[`${name}/package.json`] = JSON.stringify({
      name: name.toLowerCase().replace(/\s+/g, "-"),
      version: "1.0.0",
      description: `Generated ${config.type} project`,
      scripts: {
        dev: config.stack.includes("nextjs") ? "next dev" : "node index.js",
        build: config.stack.includes("nextjs") ? "next build" : "echo 'Build script'",
        start: config.stack.includes("nextjs") ? "next start" : "node index.js",
      },
      dependencies,
    }, null, 2);

    // TypeScript config
    if (config.features.includes("TypeScript")) {
      structure[`${name}/tsconfig.json`] = JSON.stringify({
        compilerOptions: {
          target: "ES2020",
          module: "commonjs",
          lib: ["ES2020"],
          outDir: "./dist",
          rootDir: "./src",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
        },
        include: ["src/**/*"],
        exclude: ["node_modules"],
      }, null, 2);
    }

    // Main entry point
    if (config.type === "website" && config.stack.includes("react")) {
      structure[`${name}/src/App.tsx`] = `import React from 'react';\n\nfunction App() {\n  return (\n    <div className="App">\n      <h1>Welcome to ${config.name}</h1>\n    </div>\n  );\n}\n\nexport default App;\n`;
      structure[`${name}/src/index.tsx`] = `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n`;
      structure[`${name}/public/index.html`] = `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>${config.name}</title>\n</head>\n<body>\n  <div id="root"></div>\n</body>\n</html>\n`;
    } else if (config.type === "api" && config.stack.includes("express")) {
      structure[`${name}/src/index.ts`] = `import express from 'express';\n\nconst app = express();\nconst PORT = process.env.PORT || 3000;\n\napp.use(express.json());\n\napp.get('/', (req, res) => {\n  res.json({ message: 'Welcome to ${config.name} API' });\n});\n\napp.listen(PORT, () => {\n  console.log(\`Server running on port \${PORT}\`);\n});\n`;
    }

    // Gitignore
    structure[`${name}/.gitignore`] = `node_modules/\n.env\n.DS_Store\ndist/\nbuild/\n*.log\n`;

    // Additional config files
    if (config.features.includes("ESLint")) {
      structure[`${name}/.eslintrc.json`] = JSON.stringify({
        extends: ["eslint:recommended"],
        env: { node: true, es2020: true },
      }, null, 2);
    }

    return structure;
  }

  function handleGenerate() {
    if (!projectName.trim()) {
      alert("Please enter a project name");
      return;
    }

    if (selectedStack.length === 0) {
      alert("Please select at least one technology stack");
      return;
    }

    const config: ProjectConfig = {
      name: projectName,
      type: projectType,
      stack: selectedStack,
      features: selectedFeatures,
    };

    const structure = generateProjectStructure(config);
    setProjectStructure(structure);
    setGenerated(true);
  }

  function handleDownload() {
    if (Object.keys(projectStructure).length === 0) return;

    // Create a zip-like structure (simplified - in production, use a zip library)
    const files = Object.entries(projectStructure)
      .map(([path, content]) => `=== ${path} ===\n${content}\n`)
      .join("\n\n");

    const blob = new Blob([files], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${projectName || "project"}-structure.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function handleReset() {
    setProjectName("");
    setProjectType("website");
    setSelectedStack([]);
    setSelectedFeatures([]);
    setGenerated(false);
    setProjectStructure({});
  }

  return (
    <SecureErrorBoundary studio="dev-studio">
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-sky-50/30 to-slate-50">
        <div className="mx-auto max-w-7xl px-4 py-6 sm:py-8 sm:px-6 lg:px-8">
          {/* Header */}
          <header className="mb-6 sm:mb-8">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
              <div className="flex items-center gap-3">
                <Link
                  href="/dev-studio"
                  className="text-slate-600 hover:text-slate-900 transition-colors"
                  aria-label="Back to Dev Studio"
                >
                  <ArrowLeft className="w-5 h-5" />
                </Link>
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-sky-500 to-sky-600 text-white">
                  <Code className="w-6 h-6" />
                </div>
                <div>
                  <h1 className="text-3xl sm:text-4xl font-bold text-slate-900">Project Builder</h1>
                  <p className="text-base sm:text-lg text-slate-600 mt-1">
                    Visual project scaffolding with stack selection
                  </p>
                </div>
                <HelpTooltip
                  title="Project Builder"
                  content={
                    <div className="space-y-4">
                      <p>
                        The Project Builder helps you create the starting structure for new software projects. 
                        It sets up all the files and folders you need to start coding.
                      </p>
                      <div>
                        <h3 className="font-semibold text-slate-900 mb-2">Features:</h3>
                        <ul className="list-disc list-inside space-y-1 text-sm text-slate-700">
                          <li>Choose project type (website, API, mobile app, etc.)</li>
                          <li>Select technology stack</li>
                          <li>Generate project structure</li>
                          <li>Export configuration files</li>
                        </ul>
                      </div>
                    </div>
                  }
                />
              </div>
              <StudioNavigation studioType="dev" showHub={true} />
            </div>
          </header>

          {/* Main Content */}
          <div className="rounded-3xl bg-white border border-slate-200 p-8 shadow-sm">
            {/* Credit Estimate */}
            <div className="mb-6">
              <CreditEstimate toolId="dev-studio-projects" />
            </div>

            {!generated ? (
              <div className="space-y-6">
                {/* Project Name */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Project Name
                  </label>
                  <input
                    type="text"
                    value={projectName}
                    onChange={(e) => setProjectName(e.target.value)}
                    placeholder="my-awesome-project"
                    className="w-full rounded-lg border border-slate-300 px-4 py-2 text-slate-900 focus:border-sky-500 focus:ring-2 focus:ring-sky-500"
                  />
                </div>

                {/* Project Type */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Project Type
                  </label>
                  <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                    {projectTypes.map((type) => (
                      <button
                        key={type.value}
                        onClick={() => {
                          setProjectType(type.value);
                          setSelectedStack([]); // Reset stack when type changes
                        }}
                        className={`p-4 rounded-lg border-2 text-left transition-all ${
                          projectType === type.value
                            ? "border-sky-500 bg-sky-50"
                            : "border-slate-200 hover:border-slate-300"
                        }`}
                      >
                        <div className="font-semibold text-slate-900">{type.label}</div>
                        <div className="text-xs text-slate-600 mt-1">{type.description}</div>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Technology Stack */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Technology Stack
                  </label>
                  <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                    {stacks[projectType].map((stack) => (
                      <button
                        key={stack.value}
                        onClick={() => {
                          if (selectedStack.includes(stack.value)) {
                            setSelectedStack(selectedStack.filter((s) => s !== stack.value));
                          } else {
                            setSelectedStack([...selectedStack, stack.value]);
                          }
                        }}
                        className={`p-3 rounded-lg border-2 text-left transition-all ${
                          selectedStack.includes(stack.value)
                            ? "border-sky-500 bg-sky-50"
                            : "border-slate-200 hover:border-slate-300"
                        }`}
                      >
                        <div className="font-medium text-slate-900">{stack.label}</div>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Features */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Additional Features
                  </label>
                  <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                    {availableFeatures[projectType].map((feature) => (
                      <label
                        key={feature}
                        className="flex items-center gap-2 p-2 rounded-lg border border-slate-200 hover:bg-slate-50 cursor-pointer"
                      >
                        <input
                          type="checkbox"
                          checked={selectedFeatures.includes(feature)}
                          onChange={(e) => {
                            if (e.target.checked) {
                              setSelectedFeatures([...selectedFeatures, feature]);
                            } else {
                              setSelectedFeatures(selectedFeatures.filter((f) => f !== feature));
                            }
                          }}
                          className="rounded border-slate-300 text-sky-600 focus:ring-sky-500"
                        />
                        <span className="text-sm text-slate-700">{feature}</span>
                      </label>
                    ))}
                  </div>
                </div>

                {/* Generate Button */}
                <div className="pt-4">
                  <button
                    onClick={handleGenerate}
                    disabled={!projectName.trim() || selectedStack.length === 0}
                    className="w-full sm:w-auto px-6 py-3 bg-sky-600 hover:bg-sky-700 text-white rounded-lg font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Generate Project Structure
                  </button>
                </div>
              </div>
            ) : (
              <div className="space-y-6">
                <div className="flex items-center gap-2 text-emerald-600">
                  <CheckCircle2 className="w-5 h-5" />
                  <span className="font-semibold">Project structure generated successfully!</span>
                </div>

                {/* Project Structure Preview */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-900 mb-3">Generated Files</h3>
                  <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 max-h-96 overflow-y-auto">
                    <div className="space-y-1 font-mono text-sm">
                      {Object.keys(projectStructure).map((path) => (
                        <div key={path} className="flex items-center gap-2 text-slate-700">
                          <Folder className="w-4 h-4 text-slate-500" />
                          <span>{path}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex flex-col sm:flex-row gap-3">
                  <button
                    onClick={handleDownload}
                    className="flex items-center justify-center gap-2 px-6 py-3 bg-sky-600 hover:bg-sky-700 text-white rounded-lg font-semibold transition-colors"
                  >
                    <Download className="w-4 h-4" />
                    Download Structure
                  </button>
                  <button
                    onClick={handleReset}
                    className="px-6 py-3 bg-white hover:bg-slate-50 text-slate-900 border border-slate-300 rounded-lg font-semibold transition-colors"
                  >
                    Create Another Project
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </SecureErrorBoundary>
  );
}
