"use client";

import React, { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Database, HelpCircle, Plus, Trash2, Download, CheckCircle2, Link2 } from "lucide-react";
import SecureErrorBoundary from "@/components/studios/SecureErrorBoundary";
import StudioNavigation from "@/components/studios/StudioNavigation";
import HelpTooltip from "@/components/studios/HelpTooltip";
import CreditEstimate from "@/components/studios/CreditEstimate";

type FieldType = "string" | "number" | "boolean" | "date" | "text" | "json";

interface Field {
  id: string;
  name: string;
  type: FieldType;
  nullable: boolean;
  unique: boolean;
  primaryKey: boolean;
  defaultValue?: string;
}

interface Table {
  id: string;
  name: string;
  fields: Field[];
}

interface Relationship {
  id: string;
  fromTable: string;
  fromField: string;
  toTable: string;
  toField: string;
  type: "one-to-one" | "one-to-many" | "many-to-many";
}

export default function SchemaDesignerPage() {
  const [tables, setTables] = useState<Table[]>([]);
  const [relationships, setRelationships] = useState<Relationship[]>([]);
  const [selectedTable, setSelectedTable] = useState<string | null>(null);
  const [generated, setGenerated] = useState(false);
  const [sqlScript, setSqlScript] = useState<string>("");

  function addTable() {
    const newTable: Table = {
      id: Date.now().toString(),
      name: `table_${tables.length + 1}`,
      fields: [
        {
          id: Date.now().toString() + "_1",
          name: "id",
          type: "number",
          nullable: false,
          unique: true,
          primaryKey: true,
          defaultValue: "AUTO_INCREMENT",
        },
      ],
    };
    setTables([...tables, newTable]);
    setSelectedTable(newTable.id);
  }

  function removeTable(id: string) {
    setTables(tables.filter((t) => t.id !== id));
    setRelationships(relationships.filter((r) => r.fromTable !== id && r.toTable !== id));
    if (selectedTable === id) {
      setSelectedTable(null);
    }
  }

  function updateTable(id: string, updates: Partial<Table>) {
    setTables(tables.map((t) => (t.id === id ? { ...t, ...updates } : t)));
  }

  function addField(tableId: string) {
    const table = tables.find((t) => t.id === tableId);
    if (!table) return;

    const newField: Field = {
      id: Date.now().toString(),
      name: "new_field",
      type: "string",
      nullable: true,
      unique: false,
      primaryKey: false,
    };

    updateTable(tableId, {
      fields: [...table.fields, newField],
    });
  }

  function removeField(tableId: string, fieldId: string) {
    const table = tables.find((t) => t.id === tableId);
    if (!table) return;

    updateTable(tableId, {
      fields: table.fields.filter((f) => f.id !== fieldId),
    });
  }

  function updateField(tableId: string, fieldId: string, updates: Partial<Field>) {
    const table = tables.find((t) => t.id === tableId);
    if (!table) return;

    updateTable(tableId, {
      fields: table.fields.map((f) => (f.id === fieldId ? { ...f, ...updates } : f)),
    });
  }

  function addRelationship() {
    if (tables.length < 2) {
      alert("You need at least 2 tables to create a relationship");
      return;
    }

    const newRelationship: Relationship = {
      id: Date.now().toString(),
      fromTable: tables[0].id,
      fromField: tables[0].fields[0]?.id || "",
      toTable: tables[1].id,
      toField: tables[1].fields[0]?.id || "",
      type: "one-to-many",
    };
    setRelationships([...relationships, newRelationship]);
  }

  function removeRelationship(id: string) {
    setRelationships(relationships.filter((r) => r.id !== id));
  }

  function updateRelationship(id: string, updates: Partial<Relationship>) {
    setRelationships(relationships.map((r) => (r.id === id ? { ...r, ...updates } : r)));
  }

  function generateSQL() {
    if (tables.length === 0) {
      alert("Please add at least one table");
      return;
    }

    let sql = "-- Generated by Ransford's Notes Schema Designer\n\n";

    tables.forEach((table) => {
      sql += `CREATE TABLE ${table.name} (\n`;
      const fieldDefinitions = table.fields.map((field) => {
        let def = `  ${field.name} `;

        switch (field.type) {
          case "string":
            def += "VARCHAR(255)";
            break;
          case "number":
            def += "INT";
            break;
          case "boolean":
            def += "BOOLEAN";
            break;
          case "date":
            def += "DATE";
            break;
          case "text":
            def += "TEXT";
            break;
          case "json":
            def += "JSON";
            break;
        }

        if (!field.nullable) {
          def += " NOT NULL";
        }

        if (field.unique) {
          def += " UNIQUE";
        }

        if (field.primaryKey) {
          def += " PRIMARY KEY";
        }

        if (field.defaultValue) {
          def += ` DEFAULT ${field.defaultValue}`;
        }

        return def;
      });

      sql += fieldDefinitions.join(",\n");
      sql += "\n);\n\n";
    });

    // Add foreign keys for relationships
    relationships.forEach((rel) => {
      const fromTable = tables.find((t) => t.id === rel.fromTable);
      const toTable = tables.find((t) => t.id === rel.toTable);
      const fromField = fromTable?.fields.find((f) => f.id === rel.fromField);
      const toField = toTable?.fields.find((f) => f.id === rel.toField);

      if (fromTable && toTable && fromField && toField) {
        sql += `ALTER TABLE ${fromTable.name}\n`;
        sql += `  ADD CONSTRAINT fk_${fromTable.name}_${toTable.name}\n`;
        sql += `  FOREIGN KEY (${fromField.name}) REFERENCES ${toTable.name}(${toField.name});\n\n`;
      }
    });

    setSqlScript(sql);
    setGenerated(true);
  }

  function handleDownload() {
    if (!sqlScript) return;
    const blob = new Blob([sqlScript], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "schema.sql";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function handleReset() {
    setTables([]);
    setRelationships([]);
    setSelectedTable(null);
    setGenerated(false);
    setSqlScript("");
  }

  const selectedTableData = tables.find((t) => t.id === selectedTable);

  return (
    <SecureErrorBoundary studio="dev-studio">
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-indigo-50/30 to-slate-50">
        <div className="mx-auto max-w-7xl px-4 py-6 sm:py-8 sm:px-6 lg:px-8">
          <header className="mb-6 sm:mb-8">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
              <div className="flex items-center gap-3">
                <Link
                  href="/dev-studio"
                  className="text-slate-600 hover:text-slate-900 transition-colors"
                  aria-label="Back to Dev Studio"
                >
                  <ArrowLeft className="w-5 h-5" />
                </Link>
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 to-indigo-600 text-white">
                  <Database className="w-6 h-6" />
                </div>
                <div>
                  <h1 className="text-3xl sm:text-4xl font-bold text-slate-900">Database Schema Designer</h1>
                  <p className="text-base sm:text-lg text-slate-600 mt-1">Visual schema builder with migration generation</p>
                </div>
                <HelpTooltip
                  title="Database Schema Designer"
                  content={
                    <div className="space-y-4">
                      <p>
                        The Schema Designer helps you plan how information is organized in a database. 
                        A database is like a digital filing cabinet, and a schema is like the labels 
                        and folders you use to organize information.
                      </p>
                      <div>
                        <h3 className="font-semibold text-slate-900 mb-2">Features:</h3>
                        <ul className="list-disc list-inside space-y-1 text-sm text-slate-700">
                          <li>Create tables and define fields</li>
                          <li>Set up relationships between tables</li>
                          <li>Validate schema design</li>
                          <li>Generate migration scripts</li>
                        </ul>
                      </div>
                    </div>
                  }
                />
              </div>
              <StudioNavigation studioType="dev" showHub={true} />
            </div>
          </header>

          <div className="rounded-3xl bg-white border border-slate-200 p-8 shadow-sm">
            {/* Credit Estimate */}
            <div className="mb-6">
              <CreditEstimate toolId="dev-studio-schema-designer" />
            </div>

            {!generated ? (
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Tables List */}
                <div className="lg:col-span-1">
                  <div className="flex items-center justify-between mb-3">
                    <h3 className="text-lg font-semibold text-slate-900">Tables</h3>
                    <button
                      onClick={addTable}
                      className="flex items-center gap-2 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-semibold transition-colors"
                    >
                      <Plus className="w-4 h-4" />
                      Add Table
                    </button>
                  </div>
                  <div className="space-y-2">
                    {tables.map((table) => (
                      <button
                        key={table.id}
                        onClick={() => setSelectedTable(table.id)}
                        className={`w-full p-3 rounded-lg border-2 text-left transition-all ${
                          selectedTable === table.id
                            ? "border-indigo-500 bg-indigo-50"
                            : "border-slate-200 hover:border-slate-300"
                        }`}
                      >
                        <div className="font-semibold text-slate-900">{table.name}</div>
                        <div className="text-xs text-slate-600 mt-1">{table.fields.length} fields</div>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Table Editor */}
                <div className="lg:col-span-2">
                  {selectedTableData ? (
                    <div className="space-y-4">
                      <div>
                        <label className="block text-sm font-medium text-slate-700 mb-2">Table Name</label>
                        <input
                          type="text"
                          value={selectedTableData.name}
                          onChange={(e) => updateTable(selectedTableData.id, { name: e.target.value })}
                          className="w-full rounded-lg border border-slate-300 px-4 py-2 text-slate-900 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
                        />
                      </div>

                      <div>
                        <div className="flex items-center justify-between mb-3">
                          <label className="block text-sm font-medium text-slate-700">Fields</label>
                          <button
                            onClick={() => addField(selectedTableData.id)}
                            className="flex items-center gap-2 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-semibold transition-colors"
                          >
                            <Plus className="w-4 h-4" />
                            Add Field
                          </button>
                        </div>
                        <div className="space-y-3">
                          {selectedTableData.fields.map((field) => (
                            <div key={field.id} className="p-4 rounded-lg border border-slate-200 bg-slate-50">
                              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-3">
                                <input
                                  type="text"
                                  value={field.name}
                                  onChange={(e) => updateField(selectedTableData.id, field.id, { name: e.target.value })}
                                  placeholder="Field name"
                                  className="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
                                />
                                <select
                                  value={field.type}
                                  onChange={(e) =>
                                    updateField(selectedTableData.id, field.id, { type: e.target.value as FieldType })
                                  }
                                  className="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
                                >
                                  <option value="string">String</option>
                                  <option value="number">Number</option>
                                  <option value="boolean">Boolean</option>
                                  <option value="date">Date</option>
                                  <option value="text">Text</option>
                                  <option value="json">JSON</option>
                                </select>
                              </div>
                              <div className="flex flex-wrap gap-3 mb-3">
                                <label className="flex items-center gap-2 cursor-pointer">
                                  <input
                                    type="checkbox"
                                    checked={field.nullable}
                                    onChange={(e) => updateField(selectedTableData.id, field.id, { nullable: e.target.checked })}
                                    className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                                  />
                                  <span className="text-sm text-slate-700">Nullable</span>
                                </label>
                                <label className="flex items-center gap-2 cursor-pointer">
                                  <input
                                    type="checkbox"
                                    checked={field.unique}
                                    onChange={(e) => updateField(selectedTableData.id, field.id, { unique: e.target.checked })}
                                    className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                                  />
                                  <span className="text-sm text-slate-700">Unique</span>
                                </label>
                                <label className="flex items-center gap-2 cursor-pointer">
                                  <input
                                    type="checkbox"
                                    checked={field.primaryKey}
                                    onChange={(e) => updateField(selectedTableData.id, field.id, { primaryKey: e.target.checked })}
                                    className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                                  />
                                  <span className="text-sm text-slate-700">Primary Key</span>
                                </label>
                              </div>
                              <div className="flex items-center justify-between">
                                <input
                                  type="text"
                                  value={field.defaultValue || ""}
                                  onChange={(e) => updateField(selectedTableData.id, field.id, { defaultValue: e.target.value })}
                                  placeholder="Default value (optional)"
                                  className="flex-1 rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 mr-2"
                                />
                                <button
                                  onClick={() => removeField(selectedTableData.id, field.id)}
                                  className="px-3 py-2 bg-red-50 hover:bg-red-100 text-red-600 rounded-lg transition-colors"
                                >
                                  <Trash2 className="w-4 h-4" />
                                </button>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-12 text-slate-500">
                      <Database className="w-12 h-12 mx-auto mb-2 opacity-50" />
                      <p>Select a table to edit, or create a new one.</p>
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="space-y-6">
                <div className="flex items-center gap-2 text-emerald-600">
                  <CheckCircle2 className="w-5 h-5" />
                  <span className="font-semibold">SQL migration script generated successfully!</span>
                </div>

                {/* SQL Preview */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-900 mb-3">SQL Migration Script</h3>
                  <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 max-h-96 overflow-y-auto">
                    <pre className="text-xs font-mono text-slate-700 whitespace-pre-wrap">{sqlScript}</pre>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex flex-col sm:flex-row gap-3">
                  <button
                    onClick={handleDownload}
                    className="flex items-center justify-center gap-2 px-6 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-semibold transition-colors"
                  >
                    <Download className="w-4 h-4" />
                    Download SQL Script
                  </button>
                  <button
                    onClick={handleReset}
                    className="px-6 py-3 bg-white hover:bg-slate-50 text-slate-900 border border-slate-300 rounded-lg font-semibold transition-colors"
                  >
                    Create Another Schema
                  </button>
                </div>
              </div>
            )}

            {/* Generate Button */}
            {!generated && (
              <div className="mt-6 pt-6 border-t border-slate-200">
                <button
                  onClick={generateSQL}
                  disabled={tables.length === 0}
                  className="w-full sm:w-auto px-6 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Generate SQL Migration
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </SecureErrorBoundary>
  );
}
