"use client";

import React, { useState } from "react";
import Link from "next/link";
import ToolShell from "@/components/tools/ToolShell";
import { getToolContract } from "@/lib/tools/loadContract";
import { createToolError } from "@/components/tools/ErrorPanel";
import type { ToolContract, ExecutionMode } from "@/components/tools/ToolShell";

const contract = getToolContract("incident-postmortem-builder");

const examples = [
  {
    title: "Database Outage Example",
    inputs: {
      title: "Production Database Outage",
      dateTime: new Date(Date.now() - 86400000).toISOString().slice(0, 16),
      impact: "Service unavailable for 2 hours, affecting 15,000 users",
      timeline: [
        "10:30 AM - Database connection pool exhausted",
        "10:35 AM - Alert triggered, on-call engineer notified",
        "10:45 AM - Identified runaway query consuming all connections",
        "11:15 AM - Query killed, connection pool restored",
        "11:30 AM - Service fully recovered",
      ],
      rootCauses: [
        "Missing query timeout configuration",
        "No connection pool monitoring alerts",
        "Query optimization skipped during last release",
      ],
      actionItems: [
        "Add query timeout of 30 seconds",
        "Implement connection pool monitoring",
        "Review and optimize slow queries in next sprint",
      ],
    },
  },
  {
    title: "API Rate Limit Incident",
    inputs: {
      title: "Third-Party API Rate Limit Exceeded",
      dateTime: new Date(Date.now() - 172800000).toISOString().slice(0, 16),
      impact: "Payment processing delayed for 1 hour",
      timeline: [
        "2:00 PM - Payment API returns 429 errors",
        "2:05 PM - Checked rate limit dashboard",
        "2:10 PM - Identified burst of requests from retry logic",
        "2:30 PM - Implemented exponential backoff",
        "3:00 PM - All pending payments processed",
      ],
      rootCauses: [
        "Aggressive retry logic without backoff",
        "No rate limit monitoring",
        "Missing circuit breaker pattern",
      ],
      actionItems: [
        "Implement exponential backoff for retries",
        "Add rate limit monitoring dashboard",
        "Implement circuit breaker for external APIs",
      ],
    },
  },
  {
    title: "Security Breach Exercise",
    inputs: {
      title: "Unauthorized Access Attempt",
      dateTime: new Date().toISOString().slice(0, 16),
      impact: "Attempted unauthorized access detected and blocked",
      timeline: [
        "9:00 AM - Unusual login patterns detected",
        "9:05 AM - Security team notified",
        "9:10 AM - Access blocked, user account suspended",
        "9:15 AM - Logs reviewed, confirmed attack vector",
      ],
      rootCauses: [
        "Weak password policy",
        "No MFA enforcement for admin accounts",
      ],
      actionItems: [
        "Enforce stronger password requirements",
        "Require MFA for all admin accounts",
        "Review access logs weekly",
      ],
    },
  },
];

export default function IncidentPostMortemBuilderPage() {
  const [title, setTitle] = useState("");
  const [dateTime, setDateTime] = useState(new Date().toISOString().slice(0, 16));
  const [impact, setImpact] = useState("");
  const [timeline, setTimeline] = useState<string[]>([""]);
  const [rootCauses, setRootCauses] = useState<string[]>([""]);
  const [actionItems, setActionItems] = useState<string[]>([""]);

  if (!contract) {
    return (
      <div className="mx-auto max-w-4xl p-6">
        <p className="text-red-600">Tool contract not found.</p>
      </div>
    );
  }

  const handleRun = async (mode: ExecutionMode, inputs: Record<string, unknown>) => {
    const t = inputs.title as string;
    const dt = inputs.dateTime as string;
    const imp = inputs.impact as string;

    if (!t || t.trim().length === 0) {
      return {
        success: false,
        error: createToolError("missing_required_fields", "incident-postmortem-builder", { field: "title" }),
      };
    }

    const validTimeline = (inputs.timeline as string[]).filter((e) => e.trim().length > 0);
    const validRootCauses = (inputs.rootCauses as string[]).filter((c) => c.trim().length > 0);
    const validActionItems = (inputs.actionItems as string[]).filter((a) => a.trim().length > 0);

    const markdown = `# Post-Incident Review: ${t}

## Incident Details
- **Date/Time**: ${dt}
- **Impact**: ${imp || "Not specified"}

## Timeline
${validTimeline.length > 0 ? validTimeline.map((e, i) => `${i + 1}. ${e}`).join("\n") : "No timeline events recorded"}

## Root Causes
${validRootCauses.length > 0 ? validRootCauses.map((c, i) => `${i + 1}. ${c}`).join("\n") : "No root causes identified"}

## Action Items
${validActionItems.length > 0 ? validActionItems.map((a, i) => `${i + 1}. ${a}`).join("\n") : "No action items defined"}

## Learning Points
- Document what went well
- Document what could be improved
- Update runbooks and procedures

---
*Generated by RansfordsNotes Incident Post-Mortem Builder*`;

    return { success: true, output: markdown };
  };

  const updateArray = (setter: React.Dispatch<React.SetStateAction<string[]>>, index: number, value: string) => {
    setter((prev) => {
      const newArr = [...prev];
      newArr[index] = value;
      return newArr;
    });
  };

  return (
    <div className="mx-auto max-w-6xl p-6">
      <nav className="mb-4">
        <Link href="/tools" className="text-sm font-semibold text-blue-700 hover:underline">
          ← Back to Tools
        </Link>
      </nav>

      <ToolShell contract={contract} onRun={handleRun} examples={examples} initialInputs={{ title, dateTime, impact, timeline, rootCauses, actionItems }}>
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label htmlFor="title" className="block text-sm font-semibold text-slate-900">
                Title <span className="text-red-600">*</span>
              </label>
              <input
                id="title"
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                maxLength={200}
                className="mt-2 w-full rounded-lg border border-slate-300 p-3 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
                placeholder="Incident title"
              />
            </div>
            <div>
              <label htmlFor="dateTime" className="block text-sm font-semibold text-slate-900">
                Date/Time
              </label>
              <input
                id="dateTime"
                type="datetime-local"
                value={dateTime}
                onChange={(e) => setDateTime(e.target.value)}
                className="mt-2 w-full rounded-lg border border-slate-300 p-3 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
              />
            </div>
          </div>
          <div>
            <label htmlFor="impact" className="block text-sm font-semibold text-slate-900">
              Impact
            </label>
            <textarea
              id="impact"
              value={impact}
              onChange={(e) => setImpact(e.target.value)}
              rows={3}
              maxLength={1000}
              className="mt-2 w-full rounded-lg border border-slate-300 p-3 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
              placeholder="What was affected and to what extent?"
            />
          </div>
          <div>
            <label className="block text-sm font-semibold text-slate-900 mb-2">Timeline Events (max 50)</label>
            {timeline.map((e, idx) => (
              <input
                key={idx}
                type="text"
                value={e}
                onChange={(ev) => updateArray(setTimeline, idx, ev.target.value)}
                maxLength={500}
                className="mt-2 w-full rounded-lg border border-slate-300 p-2 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
                placeholder={`Event ${idx + 1}`}
              />
            ))}
            {timeline.length < 50 && (
              <button
                type="button"
                onClick={() => setTimeline([...timeline, ""])}
                className="mt-2 text-xs text-slate-600 underline"
              >
                + Add Event
              </button>
            )}
          </div>
          <div>
            <label className="block text-sm font-semibold text-slate-900 mb-2">Root Causes (max 20)</label>
            {rootCauses.map((c, idx) => (
              <input
                key={idx}
                type="text"
                value={c}
                onChange={(e) => updateArray(setRootCauses, idx, e.target.value)}
                maxLength={500}
                className="mt-2 w-full rounded-lg border border-slate-300 p-2 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
                placeholder={`Root cause ${idx + 1}`}
              />
            ))}
            {rootCauses.length < 20 && (
              <button
                type="button"
                onClick={() => setRootCauses([...rootCauses, ""])}
                className="mt-2 text-xs text-slate-600 underline"
              >
                + Add Root Cause
              </button>
            )}
          </div>
          <div>
            <label className="block text-sm font-semibold text-slate-900 mb-2">Action Items (max 30)</label>
            {actionItems.map((a, idx) => (
              <input
                key={idx}
                type="text"
                value={a}
                onChange={(e) => updateArray(setActionItems, idx, e.target.value)}
                maxLength={500}
                className="mt-2 w-full rounded-lg border border-slate-300 p-2 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
                placeholder={`Action item ${idx + 1}`}
              />
            ))}
            {actionItems.length < 30 && (
              <button
                type="button"
                onClick={() => setActionItems([...actionItems, ""])}
                className="mt-2 text-xs text-slate-600 underline"
              >
                + Add Action Item
              </button>
            )}
          </div>
        </div>
      </ToolShell>
    </div>
  );
}

