"use client";

import React, { useState } from "react";
import Link from "next/link";
import ToolShell from "@/components/tools/ToolShell";
import { getToolContract } from "@/lib/tools/loadContract";
import { createToolError } from "@/components/tools/ErrorPanel";
import type { ToolContract, ExecutionMode } from "@/components/tools/ToolShell";

const contract = getToolContract("threat-modelling-lite");

export default function ThreatModellingLitePage() {
  const [systemName, setSystemName] = useState("");
  const [assets, setAssets] = useState<string[]>([""]);
  const [trustBoundaries, setTrustBoundaries] = useState<string[]>([""]);
  const [threats, setThreats] = useState<string[]>([""]);

  if (!contract) {
    return (
      <div className="mx-auto max-w-4xl p-6">
        <p className="text-red-600">Tool contract not found.</p>
      </div>
    );
  }

  const handleRun = async (mode: ExecutionMode, inputs: Record<string, unknown>) => {
    const system = inputs.systemName as string;
    const assetsInput = inputs.assets as string[];
    const boundariesInput = inputs.trustBoundaries as string[];
    const threatsInput = inputs.threats as string[];

    if (!system || system.trim().length === 0) {
      return {
        success: false,
        error: createToolError("validation_error", "threat-modelling-lite", { field: "systemName" }),
      };
    }

    const validAssets = assetsInput.filter((a) => a.trim().length > 0);
    if (validAssets.length === 0) {
      return {
        success: false,
        error: createToolError("missing_assets", "threat-modelling-lite", { message: "At least one asset is required" }),
      };
    }

    const strideThreats = [
      "Spoofing: Can an attacker impersonate a user or system?",
      "Tampering: Can data be modified in transit or at rest?",
      "Repudiation: Can actions be denied?",
      "Information Disclosure: Can sensitive data be leaked?",
      "Denial of Service: Can the system be made unavailable?",
      "Elevation of Privilege: Can privileges be escalated?",
    ];

    const markdown = `# Threat Model: ${system}

## Assets
${validAssets.map((a, i) => `${i + 1}. ${a}`).join("\n")}

## Trust Boundaries
${boundariesInput.filter((b) => b.trim().length > 0).map((b, i) => `${i + 1}. ${b}`).join("\n") || "None specified"}

## Identified Threats
${threatsInput.filter((t) => t.trim().length > 0).map((t, i) => `${i + 1}. ${t}`).join("\n") || "None specified"}

## STRIDE Analysis
${strideThreats.map((t, i) => `${i + 1}. ${t}`).join("\n")}

## Recommendations
- Review trust boundaries and minimize attack surface
- Implement defense in depth
- Log and monitor access to critical assets
- Regular security reviews

---
*Generated by RansfordsNotes Threat Modelling Lite*`;

    return { success: true, output: markdown };
  };

  const updateArray = (setter: React.Dispatch<React.SetStateAction<string[]>>, index: number, value: string) => {
    setter((prev) => {
      const newArr = [...prev];
      newArr[index] = value;
      return newArr;
    });
  };

  const addToArray = (setter: React.Dispatch<React.SetStateAction<string[]>>, max: number) => {
    setter((prev) => (prev.length < max ? [...prev, ""] : prev));
  };

  return (
    <div className="mx-auto max-w-6xl p-6">
      <nav className="mb-4">
        <Link href="/tools" className="text-sm font-semibold text-blue-700 hover:underline">
          ← Back to Tools
        </Link>
      </nav>

      <ToolShell contract={contract} onRun={handleRun} initialInputs={{ systemName, assets, trustBoundaries, threats }}>
        <div className="space-y-6">
          <div>
            <label htmlFor="systemName" className="block text-sm font-semibold text-slate-900">
              System Name <span className="text-red-600">*</span>
            </label>
            <input
              id="systemName"
              type="text"
              value={systemName}
              onChange={(e) => setSystemName(e.target.value)}
              maxLength={200}
              className="mt-2 w-full rounded-lg border border-slate-300 p-3 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
              placeholder="Name of the system or feature"
            />
          </div>
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="block text-sm font-semibold text-slate-900">Assets (max 20)</label>
              {assets.length < 20 && (
                <button type="button" onClick={() => addToArray(setAssets, 20)} className="text-xs text-slate-600 underline">
                  + Add Asset
                </button>
              )}
            </div>
            {assets.map((asset, idx) => (
              <input
                key={idx}
                type="text"
                value={asset}
                onChange={(e) => updateArray(setAssets, idx, e.target.value)}
                maxLength={200}
                className="mt-2 w-full rounded-lg border border-slate-300 p-2 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
                placeholder={`Asset ${idx + 1}`}
              />
            ))}
          </div>
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="block text-sm font-semibold text-slate-900">Trust Boundaries (max 10)</label>
              {trustBoundaries.length < 10 && (
                <button type="button" onClick={() => addToArray(setTrustBoundaries, 10)} className="text-xs text-slate-600 underline">
                  + Add Boundary
                </button>
              )}
            </div>
            {trustBoundaries.map((boundary, idx) => (
              <input
                key={idx}
                type="text"
                value={boundary}
                onChange={(e) => updateArray(setTrustBoundaries, idx, e.target.value)}
                maxLength={200}
                className="mt-2 w-full rounded-lg border border-slate-300 p-2 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
                placeholder={`Trust boundary ${idx + 1}`}
              />
            ))}
          </div>
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="block text-sm font-semibold text-slate-900">Threats (max 30)</label>
              {threats.length < 30 && (
                <button type="button" onClick={() => addToArray(setThreats, 30)} className="text-xs text-slate-600 underline">
                  + Add Threat
                </button>
              )}
            </div>
            {threats.map((threat, idx) => (
              <input
                key={idx}
                type="text"
                value={threat}
                onChange={(e) => updateArray(setThreats, idx, e.target.value)}
                maxLength={200}
                className="mt-2 w-full rounded-lg border border-slate-300 p-2 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500"
                placeholder={`Threat ${idx + 1}`}
              />
            ))}
          </div>
        </div>
      </ToolShell>
    </div>
  );
}

