export type DashboardMode = "static" | "server" | "user";

export type DashboardConfig = {
  id: string;
  title: string;
  description: string;
  href: string;
  tags: string[];
  mode: DashboardMode;
  dataSummary: string;
  licensingSummary: string;
  lastUpdatedNote: string;
};

export const dashboards: DashboardConfig[] = [
  {
    id: "ai",
    title: "AI dashboard",
    description:
      "Explore model types, evaluation concepts, deployment risks, and real world failure patterns through charts you can query.",
    href: "/dashboards/ai",
    tags: ["AI", "Models", "Evaluation", "Governance"],
    mode: "static",
    dataSummary: "Curated educational dataset stored in this repo. No external calls required.",
    licensingSummary: "All visualisations are generated by this website. Dataset is authored for education and can be updated via PR.",
    lastUpdatedNote: "Updated when I improve the notes or add new examples.",
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity dashboard",
    description: "Practical dashboards for web posture, DNS and email security, redirects, and local storage hygiene.",
    href: "/dashboards/cybersecurity",
    tags: ["Security", "Risk", "Controls", "Detection"],
    mode: "static",
    dataSummary: "Uses simple server side lookups plus in browser inspection. No scraping of third party data beyond requested lookups.",
    licensingSummary: "Educational only. No live attack feeds or exploit tooling.",
    lastUpdatedNote: "Updated with website, DNS/email, redirect, and cookie/storage labs.",
  },
  {
    id: "architecture",
    title: "Software architecture dashboard",
    description: "Interactive sandboxes for structure, flows, boundaries, and reliability in software systems.",
    href: "/dashboards/architecture",
    tags: ["Architecture", "Design", "Reliability"],
    mode: "static",
    dataSummary: "Browser-only sandboxes to explore architecture scenarios. No external calls.",
    licensingSummary: "Educational tools and visualisations generated locally.",
    lastUpdatedNote: "Updated with the initial set of six architecture dashboards.",
  },
  {
    id: "cim",
    title: "CIM and schema dashboard",
    description: "Schema exploration, validation summaries, and example mappings. Coming later.",
    href: "/dashboards/cim",
    tags: ["CIM", "Schema", "Validation"],
    mode: "static",
    dataSummary: "Planned as locally rendered schema summaries and user provided files.",
    licensingSummary: "No official endorsement implied.",
    lastUpdatedNote: "Planned.",
  },
];
