"use client";

import React, { useState } from "react";
import Link from "next/link";
import { ArrowLeft, GitBranch, HelpCircle, Plus, Trash2, Download, CheckCircle2, Database, FileText } from "lucide-react";
import SecureErrorBoundary from "@/components/studios/SecureErrorBoundary";
import StudioNavigation from "@/components/studios/StudioNavigation";
import HelpTooltip from "@/components/studios/HelpTooltip";
import CreditEstimate from "@/components/studios/CreditEstimate";

type NodeType = "source" | "transform" | "filter" | "aggregate" | "destination";
type TransformType = "map" | "join" | "group" | "sort" | "deduplicate";

interface PipelineNode {
  id: string;
  name: string;
  type: NodeType;
  transformType?: TransformType;
  config: Record<string, unknown>;
  position: { x: number; y: number };
}

interface PipelineConnection {
  from: string;
  to: string;
}

export default function PipelinesPage() {
  const [pipelineName, setPipelineName] = useState("");
  const [nodes, setNodes] = useState<PipelineNode[]>([]);
  const [connections, setConnections] = useState<PipelineConnection[]>([]);
  const [selectedNode, setSelectedNode] = useState<string | null>(null);
  const [generated, setGenerated] = useState(false);
  const [pipelineConfig, setPipelineConfig] = useState<string>("");

  function addNode(type: NodeType) {
    const newNode: PipelineNode = {
      id: Date.now().toString(),
      name: `${type}_${nodes.length + 1}`,
      type,
      config: {},
      position: { x: nodes.length * 200, y: 100 },
    };
    setNodes([...nodes, newNode]);
    setSelectedNode(newNode.id);
  }

  function removeNode(id: string) {
    setNodes(nodes.filter((n) => n.id !== id));
    setConnections(connections.filter((c) => c.from !== id && c.to !== id));
    if (selectedNode === id) {
      setSelectedNode(null);
    }
  }

  function updateNode(id: string, updates: Partial<PipelineNode>) {
    setNodes(nodes.map((n) => (n.id === id ? { ...n, ...updates } : n)));
  }

  function addConnection(from: string, to: string) {
    if (connections.some((c) => c.from === from && c.to === to)) return;
    setConnections([...connections, { from, to }]);
  }

  function removeConnection(from: string, to: string) {
    setConnections(connections.filter((c) => !(c.from === from && c.to === to)));
  }

  function generatePipeline() {
    if (!pipelineName.trim()) {
      alert("Please enter a pipeline name");
      return;
    }

    if (nodes.length === 0) {
      alert("Please add at least one node");
      return;
    }

    const sources = nodes.filter((n) => n.type === "source");
    const destinations = nodes.filter((n) => n.type === "destination");

    if (sources.length === 0) {
      alert("Please add at least one source node");
      return;
    }

    if (destinations.length === 0) {
      alert("Please add at least one destination node");
      return;
    }

    const config = {
      name: pipelineName,
      description: "Generated by Ransford's Notes Data Pipeline Designer",
      nodes: nodes.map((node) => ({
        id: node.id,
        name: node.name,
        type: node.type,
        transformType: node.transformType,
        config: node.config,
      })),
      connections: connections,
      generatedAt: new Date().toISOString(),
    };

    setPipelineConfig(JSON.stringify(config, null, 2));
    setGenerated(true);
  }

  function handleDownload() {
    if (!pipelineConfig) return;
    const blob = new Blob([pipelineConfig], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${pipelineName || "pipeline"}-config.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function handleReset() {
    setPipelineName("");
    setNodes([]);
    setConnections([]);
    setSelectedNode(null);
    setGenerated(false);
    setPipelineConfig("");
  }

  const selectedNodeData = nodes.find((n) => n.id === selectedNode);
  const nodeTypes: { type: NodeType; label: string; icon: React.ReactNode }[] = [
    { type: "source", label: "Source", icon: <Database className="w-4 h-4" /> },
    { type: "transform", label: "Transform", icon: <FileText className="w-4 h-4" /> },
    { type: "filter", label: "Filter", icon: <FileText className="w-4 h-4" /> },
    { type: "aggregate", label: "Aggregate", icon: <FileText className="w-4 h-4" /> },
    { type: "destination", label: "Destination", icon: <Database className="w-4 h-4" /> },
  ];

  return (
    <SecureErrorBoundary studio="data-studio">
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-amber-50/30 to-slate-50">
        <div className="mx-auto max-w-7xl px-4 py-6 sm:py-8 sm:px-6 lg:px-8">
          <header className="mb-6 sm:mb-8">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
              <div className="flex items-center gap-3">
                <Link href="/data-studio" className="text-slate-600 hover:text-slate-900 transition-colors" aria-label="Back to Data Studio">
                  <ArrowLeft className="w-5 h-5" />
                </Link>
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-amber-500 to-amber-600 text-white">
                  <GitBranch className="w-6 h-6" />
                </div>
                <div>
                  <h1 className="text-3xl sm:text-4xl font-bold text-slate-900">Data Pipeline Designer</h1>
                  <p className="text-base sm:text-lg text-slate-600 mt-1">Visual ETL/ELT pipeline builder</p>
                </div>
                <HelpTooltip
                  title="Data Pipeline Designer"
                  content={
                    <div className="space-y-4">
                      <p>Design data pipelines to extract, transform, and load data from various sources.</p>
                      <div>
                        <h3 className="font-semibold text-slate-900 mb-2">Features:</h3>
                        <ul className="list-disc list-inside space-y-1 text-sm text-slate-700">
                          <li>Create source and destination nodes</li>
                          <li>Add transformation steps</li>
                          <li>Configure filters and aggregations</li>
                          <li>Export pipeline configuration</li>
                        </ul>
                      </div>
                    </div>
                  }
                />
              </div>
              <StudioNavigation studioType="data" showHub={true} />
            </div>
          </header>

          <div className="rounded-3xl bg-white border border-slate-200 p-8 shadow-sm">
            {/* Credit Estimate */}
            <div className="mb-6">
              <CreditEstimate toolId="data-studio-pipelines" />
            </div>

            {!generated ? (
              <div className="space-y-6">
                {/* Pipeline Name */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">Pipeline Name</label>
                  <input
                    type="text"
                    value={pipelineName}
                    onChange={(e) => setPipelineName(e.target.value)}
                    placeholder="My Data Pipeline"
                    className="w-full rounded-lg border border-slate-300 px-4 py-2 text-slate-900 focus:border-amber-500 focus:ring-2 focus:ring-amber-500"
                  />
                </div>

                {/* Node Types */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-3">Add Nodes</label>
                  <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
                    {nodeTypes.map((nodeType) => (
                      <button
                        key={nodeType.type}
                        onClick={() => addNode(nodeType.type)}
                        className="flex flex-col items-center gap-2 p-4 rounded-lg border-2 border-slate-200 hover:border-amber-500 hover:bg-amber-50 transition-all"
                      >
                        {nodeType.icon}
                        <span className="text-sm font-medium text-slate-700">{nodeType.label}</span>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Nodes List */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-3">Pipeline Nodes</label>
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                    {nodes.map((node) => {
                      const colorClasses = {
                        source: "bg-blue-100 text-blue-800",
                        transform: "bg-purple-100 text-purple-800",
                        filter: "bg-yellow-100 text-yellow-800",
                        aggregate: "bg-green-100 text-green-800",
                        destination: "bg-red-100 text-red-800",
                      };
                      return (
                        <div
                          key={node.id}
                          onClick={() => setSelectedNode(node.id)}
                          className={`p-4 rounded-lg border-2 cursor-pointer transition-all ${
                            selectedNode === node.id
                              ? "border-amber-500 bg-amber-50"
                              : "border-slate-200 hover:border-slate-300"
                          }`}
                        >
                          <div className="flex items-center justify-between mb-2">
                            <div className="font-semibold text-slate-900">{node.name}</div>
                            <button
                              onClick={(e) => {
                                e.stopPropagation();
                                removeNode(node.id);
                              }}
                              className="text-red-600 hover:text-red-700"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                          <span className={`px-2 py-1 rounded text-xs font-medium ${colorClasses[node.type]}`}>
                            {node.type}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Node Editor */}
                {selectedNodeData && (
                  <div className="p-6 rounded-lg border border-slate-200 bg-slate-50">
                    <h3 className="text-lg font-semibold text-slate-900 mb-4">Edit Node</h3>
                    <div className="space-y-4">
                      <div>
                        <label className="block text-sm font-medium text-slate-700 mb-2">Node Name</label>
                        <input
                          type="text"
                          value={selectedNodeData.name}
                          onChange={(e) => updateNode(selectedNodeData.id, { name: e.target.value })}
                          className="w-full rounded-lg border border-slate-300 px-4 py-2 text-slate-900 focus:border-amber-500 focus:ring-2 focus:ring-amber-500"
                        />
                      </div>
                      {selectedNodeData.type === "transform" && (
                        <div>
                          <label className="block text-sm font-medium text-slate-700 mb-2">Transform Type</label>
                          <select
                            value={selectedNodeData.transformType || "map"}
                            onChange={(e) =>
                              updateNode(selectedNodeData.id, { transformType: e.target.value as TransformType })
                            }
                            className="w-full rounded-lg border border-slate-300 px-4 py-2 text-slate-900 focus:border-amber-500 focus:ring-2 focus:ring-amber-500"
                          >
                            <option value="map">Map</option>
                            <option value="join">Join</option>
                            <option value="group">Group</option>
                            <option value="sort">Sort</option>
                            <option value="deduplicate">Deduplicate</option>
                          </select>
                        </div>
                      )}
                      {(selectedNodeData.type === "source" || selectedNodeData.type === "destination") && (
                        <div>
                          <label className="block text-sm font-medium text-slate-700 mb-2">Connection String</label>
                          <input
                            type="text"
                            value={(selectedNodeData.config.connectionString as string) || ""}
                            onChange={(e) =>
                              updateNode(selectedNodeData.id, {
                                config: { ...selectedNodeData.config, connectionString: e.target.value },
                              })
                            }
                            placeholder="jdbc:postgresql://localhost:5432/mydb"
                            className="w-full rounded-lg border border-slate-300 px-4 py-2 text-slate-900 focus:border-amber-500 focus:ring-2 focus:ring-amber-500 font-mono text-sm"
                          />
                        </div>
                      )}
                      {selectedNodeData.type === "filter" && (
                        <div>
                          <label className="block text-sm font-medium text-slate-700 mb-2">Filter Condition</label>
                          <input
                            type="text"
                            value={(selectedNodeData.config.condition as string) || ""}
                            onChange={(e) =>
                              updateNode(selectedNodeData.id, {
                                config: { ...selectedNodeData.config, condition: e.target.value },
                              })
                            }
                            placeholder="age > 18"
                            className="w-full rounded-lg border border-slate-300 px-4 py-2 text-slate-900 focus:border-amber-500 focus:ring-2 focus:ring-amber-500 font-mono text-sm"
                          />
                        </div>
                      )}
                    </div>
                  </div>
                )}

                {/* Generate Button */}
                <div className="pt-4">
                  <button
                    onClick={generatePipeline}
                    disabled={!pipelineName.trim() || nodes.length === 0}
                    className="w-full sm:w-auto px-6 py-3 bg-amber-600 hover:bg-amber-700 text-white rounded-lg font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Generate Pipeline Configuration
                  </button>
                </div>
              </div>
            ) : (
              <div className="space-y-6">
                <div className="flex items-center gap-2 text-emerald-600">
                  <CheckCircle2 className="w-5 h-5" />
                  <span className="font-semibold">Pipeline configuration generated successfully!</span>
                </div>

                {/* Pipeline Preview */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-900 mb-3">Pipeline Configuration</h3>
                  <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 max-h-96 overflow-y-auto">
                    <pre className="text-xs font-mono text-slate-700 whitespace-pre-wrap">{pipelineConfig}</pre>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex flex-col sm:flex-row gap-3">
                  <button
                    onClick={handleDownload}
                    className="flex items-center justify-center gap-2 px-6 py-3 bg-amber-600 hover:bg-amber-700 text-white rounded-lg font-semibold transition-colors"
                  >
                    <Download className="w-4 h-4" />
                    Download Configuration
                  </button>
                  <button
                    onClick={handleReset}
                    className="px-6 py-3 bg-white hover:bg-slate-50 text-slate-900 border border-slate-300 rounded-lg font-semibold transition-colors"
                  >
                    Create Another Pipeline
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </SecureErrorBoundary>
  );
}
